### ISSUE TITLE
Properties convert as camelize(:lower)

### ISSUE THREAD

**Issue by sveredyuk** [trailblazer/roar-jsonapi#21]
Any way to auto-convert properties to `camelize(:lower)` like `first_name => firstName` ?

i tried http://trailblazer.to/gems/representable/3.0/api.html#defaults but seems it doesn't work for roar json api

**Comment by myabc** [comment]
That should happen automatically. Can you post your code?

--  
Alex Coles

**Comment by sveredyuk** [comment]
all my representers inherit from `ApplicationRepresenter`:
```ruby
class ApplicationRepresenter < Representable::Decorator
  def self.resource(name)
    include Roar::JSON::JSONAPI.resource name
  end

  # include Roar::Representer::JSON

  defaults do |name, options|
    { as: name.to_s.camelize(:lower) }
  end
end

```

**Comment by myabc** [comment]
@sveredyuk if you want to make your custom camelising work, you will need to call `defaults` **AFTER** `Roar::JSON::JSONAPI.resource` is included.

Try:

```ruby
class ApplicationRepresenter < Roar::Decorator
  def self.resource(name)
    include Roar::JSON::JSONAPI.resource name

    defaults do |name, options|
      { as: name.to_s.camelize(:lower) }
    end
  end
end
```

However, if you going to use a base `ApplicationRepresenter`, I'd recommend using the lower-level [`Roar::JSON::JSONAPI::Mixin`](http://www.rubydoc.info/gems/roar-jsonapi/Roar/JSON/JSONAPI/Mixin) module and defining `type` and an `id` property yourself, e.g.

```ruby
class ApplicationRepresenter < Representable::Decorator
  include Roar::JSON::JSONAPI::Mixin

  defaults do |name, options|
    { as: name.to_s.camelize(:lower) }
  end
end

class ArticleRepresenter < ApplicationRepresenter
  type :articles
  property :id
end
```

_(N.B. I'm having second thoughts about the API design of `Roar::JSON::JSONAPI.resource` module and think it might be better to provide a base Decorator class for users to inherit from)_

**Comment by myabc** [comment]
@sveredyuk please also bear in mind that the JSON API spec [section on member names](http://jsonapi.org/format/#document-member-names) allows for lisp-case/hyphenation, so  `camelize(:lower)` shouldn't be needed

By default, [MemberName function](http://www.rubydoc.info/gems/roar-jsonapi/Roar%2FJSON%2FJSONAPI%2FMemberName:call) is called for you.

**Comment by sveredyuk** [comment]
@myabc thx  a lot

**Comment by myabc** [comment]
The example I gave may not work as expected. See #22
