### ISSUE TITLE
Compound Documents not rendered per JSONAPI standard?

### ISSUE THREAD

**Issue by KonstantinKo** [trailblazer/roar-jsonapi#27]
### Complete Description of Issue

So this seems really basic to me so I'm not sure if I'm doing anything wrong, but it seems to me like compound documents are not serialized per jsonapi standards. I tried to reproduce a simplified version of the sample given at http://jsonapi.org/format/#document-compound-documents without links and reduced number of fields:

### Steps to reproduce

```ruby
class Article < Struct.new(:id, :title, :author, :comments)
end
class Person < Struct.new(:id, :name)
end
class Comment < Struct.new(:id, :body)
end

class PersonRepresenter < Roar::Decorator
  include Roar::JSON::JSONAPI.resource :people

  attributes do
    property :name
  end
end

class CommentRepresenter < Roar:: Decorator
  include Roar::JSON::JSONAPI.resource :comments

  attributes do
    property :body
  end
end

class ArticleRepresenter < Roar:: Decorator
  include Roar::JSON::JSONAPI.resource :articles

  attributes do
    property :title
  end
  has_one :author, extend: PersonRepresenter
  has_many :comments, extend: CommentRepresenter
end

article = Article.new(
  1,
  "JSON API paints my bikeshed!",
  Person.new(9, "Dan"),
  [Comment.new(5, "First!"), Comment.new(12, "I like XML better")]
)

ArticleRepresenter.new(article).to_hash
```

### Expected behavior
Nested data `attributes` should be detailed in the `included` part. `relationships` should only contain `id` and `type`.

```ruby
{"data"=>
  {"relationships"=>
    {"author"=>
      {"data"=>{"id"=>"9", "type"=>"people"}},
     "comments"=>
      {"data"=>
        [{"id"=>"5", "type"=>"comments"},
         {"id"=>"12", "type"=>"comments"}]}},
   "id"=>"1",
   "attributes"=>{"title"=>"JSON API paints my bikeshed!"},
   "type"=>"articles"},
 "included"=>
  [{"id"=>"9", "type"=>"people", "attributes"=>{"name"=>"Dan"}},
   {"id"=>"5", "type"=>"comments", "attributes"=>{"body"=>"First!"}},
   {"id"=>"12", "type"=>"comments", "attributes"=>{"body"=>"I like XML better"}}]}
```

### Actual behavior
`relationships` contain `attributes`, `included` does not.

```ruby
{"data"=>
  {"relationships"=>
    {"author"=>
      {"data"=>{"id"=>"9", "attributes"=>{"name"=>"Dan"}, "type"=>"people"}},
     "comments"=>
      {"data"=>
        [{"id"=>"5", "attributes"=>{"body"=>"First!"}, "type"=>"comments"},
         {"id"=>"12",
          "attributes"=>{"body"=>"I like XML better"},
          "type"=>"comments"}]}},
   "id"=>"1",
   "attributes"=>{"title"=>"JSON API paints my bikeshed!"},
   "type"=>"articles"},
 "included"=>
  [{"id"=>"9", "type"=>"author"},
   {"id"=>"5", "type"=>"comments"},
   {"id"=>"12", "type"=>"comments"}]}
```

(I also just noticed a type=>author instead of people there, don't know how that happened but it is the actual console output)

### System configuration
**Roar version**: roar-edcd8efa0181
**Roar JSONAPI version**: roar-jsonapi-3ca7fa8e0f5a

**Comment by KonstantinKo** [comment]
Ohh, I figured it out. Seems like `extend:` causes the broken behaviour. It works with `decorator:`

![trap](https://cloud.githubusercontent.com/assets/779660/26209059/0d03b3e4-3bec-11e7-85cb-714b383f575f.jpg)

From the [documentation](http://trailblazer.to/gems/roar/jsonapi.html#relationships) you get the impression that they are interchangeable. I guess my feature request with this issue is to better document the difference :)

**Comment by myabc** [comment]
@KonstantinKo there was actually a typo in our code (`extends` not `extend`). Thanks for pointing this out!
