### ISSUE TITLE
How to set the type of included items?

### ISSUE THREAD

**Issue by sobakasu** [trailblazer/roar-jsonapi#40]
### Complete Description of Issue

I have a record with two 'has_one' relationships to the same type of object. I've found I can set the type using the 'type' option. However, the 'type' in the 'included' list is incorrect.

### Steps to reproduce

Here is some code that reproduces my problem. I need the 'type' in the 'included' list to be 'item'. Currently it is 'type':'second-item'.

```
require "roar/json/json_api"
require "ostruct"

class BaseModel < OpenStruct
end

class Item < BaseModel
end

class User < BaseModel
  #belongs_to :item
  #belongs_to :second_item, class_name: "Item"
end

class ItemRepresenter < Roar::Decorator
  include Roar::JSON::JSONAPI.resource :item
end

class UserRepresenter < Roar::Decorator
  include Roar::JSON::JSONAPI.resource :user
  has_one :item, extend: ItemRepresenter
  has_one :second_item, extend: ItemRepresenter, type: :item
end

user = User.new(id: 1)
user.item = Item.new(id: 1)
user.second_item = Item.new(id: 2)
puts UserRepresenter.for_collection.prepare([user]).to_json
```

### Expected behavior
`{"data":[{"relationships":{"item":{"data":{"id":"1","type":"item"}},"second-item":{"data":{"id":"2","type":"item"}}},"id":"1","type":"user"}],"included":[{"id":"1","type":"item"},{"id":"2","type":"item"}]}`

### Actual behavior
`{"data":[{"relationships":{"item":{"data":{"id":"1","type":"item"}},"second-item":{"data":{"id":"2","type":"item"}}},"id":"1","type":"user"}],"included":[{"id":"1","type":"item"},{"id":"2","type":"second-item"}]}`

### System configuration
**roar version**: 1.1.0
**roar-jsonapi version**: 0.0.3
**representable version**: 3.0.4

**Comment by seuros** [comment]
Just tried it , i get the correct output :
```
{"data":[{"relationships":{"item":{"data":{"id":"1","type":"item"}},"second-item":{"data":{"id":"2","type":"item"}}},"id":"1","type":"user"}],"included":[{"id":"1","type":"item"},{"id":"2","type":"item"}]}
```

**Comment by sobakasu** [comment]
here is my Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    declarative (0.0.10)
    declarative-option (0.1.0)
    multi_json (1.13.1)
    representable (3.0.4)
      declarative (< 0.1.0)
      declarative-option (< 0.2.0)
      uber (< 0.2.0)
    roar (1.1.0)
      representable (~> 3.0.0)
    roar-jsonapi (0.0.3)
      representable (~> 3.0, >= 3.0.3)
      roar (~> 1.1)
    uber (0.1.0)

PLATFORMS
  x64-mingw32

DEPENDENCIES
  multi_json
  roar-jsonapi

BUNDLED WITH
   2.0.2
```

**Comment by sobakasu** [comment]
it works for me with the latest roar-jsonapi source

**Comment by sobakasu** [comment]
just wondering, will version 0.0.4 be released soon? there's been a lot of changes since 0.0.3.

**Comment by seuros** [comment]
I will release it this week.
