### ISSUE TITLE
[JSON-API] Rendering an empty relationship

### ISSUE THREAD

**Issue by myabc** [trailblazer/roar-jsonapi#8]
_From @lasseebert on April 15, 2016 21:53_

I would like to render empty (`nil`) relationships with `JSONAPI` like so:

```
{
  "relationships": {
    "some_relation": { "data": null }
  }
}
```

This is what the jsonapi specification says. See http://jsonapi.org/format/#document-resource-object-linkage

When I use `render_nil: true` in a `has_one` I get

```
undefined method `each' for nil:NilClass
```

It seems like a simple issue to fix inside the `JSON::JSONAPI`. Can anyone confirm that it's not just me doing something stupid? If so I'll be happy to fix it in a pull request :)

_Copied from original issue: trailblazer/roar#189_

**Comment by myabc** [comment]
@lasseebert not sure if this issue is still relevant for you, but if it is, I'd appreciate feedback on this fix.

**Comment by lasseebert** [comment]
Hi @myabc 

The project I started with roar-jsonapi, quickly got changed to be build on Elixir instead, so I don't use this library anymore.

Judging from the test cases in the commit, it looks like your fix is exactly what I was aiming for with the issue ;)

**Comment by myabc** [comment]
@lasseebert No worries! Thanks very much for the reply.
